package model

// Identification of the original transaction.
// It corresponds to ISO 8583, field number 90 for the version 87, and 56 for the other versions.
type CardTransaction3 struct {

	// Date and time of the transaction transported unchanged by the acquirer from the card acceptor to the issuer. Corresponds to the CAPE data element TransactionIdentification/ TransactionDateTime.
	// It correspond to the ISO 8583 field number 12.
	AcceptorTransactionDateTime *ISODateTime `xml:"AccptrTxDtTm"`

	// Number generated by the transaction of the original transaction.
	InitiatorTransactionIdentification *Max35Text `xml:"InitrTxId"`

	// Identification of the entity, initiator of the transaction.
	InitiatorIdentification *Max35Text `xml:"InitrId"`
}

func (c *CardTransaction3) SetAcceptorTransactionDateTime(value string) {
	c.AcceptorTransactionDateTime = (*ISODateTime)(&value)
}

func (c *CardTransaction3) SetInitiatorTransactionIdentification(value string) {
	c.InitiatorTransactionIdentification = (*Max35Text)(&value)
}

func (c *CardTransaction3) SetInitiatorIdentification(value string) {
	c.InitiatorIdentification = (*Max35Text)(&value)
}
