package model

// Set of key elements used to refer the original transaction.
type OriginalTransactionReference13 struct {

	// Amount of money moved between the instructing agent and the instructed agent.
	InterbankSettlementAmount *ActiveOrHistoricCurrencyAndAmount `xml:"IntrBkSttlmAmt,omitempty"`

	// Amount of money to be moved between the debtor and creditor, before deduction of charges, expressed in the currency as ordered by the initiating party.
	Amount *AmountType3Choice `xml:"Amt,omitempty"`

	// Date on which the amount of money ceases to be available to the agent that owes it and when the amount of money becomes available to the agent to which it is due.
	InterbankSettlementDate *ISODate `xml:"IntrBkSttlmDt,omitempty"`

	// Date and time at which the creditor requests that the amount of money is to be collected from the debtor.
	RequestedCollectionDate *ISODate `xml:"ReqdColltnDt,omitempty"`

	// Date at which the initiating party requests the clearing agent to process the payment.
	// Usage: This is the date on which the debtor's account is to be debited. If payment by cheque, the date when the cheque must be generated by the bank.
	RequestedExecutionDate *ISODate `xml:"ReqdExctnDt,omitempty"`

	// Credit party that signs the mandate.
	CreditorSchemeIdentification *PartyIdentification32 `xml:"CdtrSchmeId,omitempty"`

	// Specifies the details on how the settlement of the original transaction(s) between the instructing agent and the instructed agent was completed.
	SettlementInformation *SettlementInformation13 `xml:"SttlmInf,omitempty"`

	// Set of elements used to further specify the type of transaction.
	PaymentTypeInformation *PaymentTypeInformation22 `xml:"PmtTpInf,omitempty"`

	// Specifies the means of payment that will be used to move the amount of money.
	PaymentMethod *PaymentMethod4Code `xml:"PmtMtd,omitempty"`

	// Set of elements used to provide further details of the mandate signed between the creditor and the debtor.
	MandateRelatedInformation *MandateRelatedInformation6 `xml:"MndtRltdInf,omitempty"`

	// Information supplied to enable the matching of an entry with the items that the transfer is intended to settle, such as commercial invoices in an accounts' receivable system.
	RemittanceInformation *RemittanceInformation5 `xml:"RmtInf,omitempty"`

	// Ultimate party that owes an amount of money to the (ultimate) creditor.
	UltimateDebtor *PartyIdentification32 `xml:"UltmtDbtr,omitempty"`

	// Party that owes an amount of money to the (ultimate) creditor.
	Debtor *PartyIdentification32 `xml:"Dbtr,omitempty"`

	// Unambiguous identification of the account of the debtor to which a debit entry will be made as a result of the transaction.
	DebtorAccount *CashAccount16 `xml:"DbtrAcct,omitempty"`

	// Financial institution servicing an account for the debtor.
	DebtorAgent *BranchAndFinancialInstitutionIdentification4 `xml:"DbtrAgt,omitempty"`

	// Unambiguous identification of the account of the debtor agent at its servicing agent in the payment chain.
	DebtorAgentAccount *CashAccount16 `xml:"DbtrAgtAcct,omitempty"`

	// Financial institution servicing an account for the creditor.
	CreditorAgent *BranchAndFinancialInstitutionIdentification4 `xml:"CdtrAgt,omitempty"`

	// Unambiguous identification of the account of the creditor agent at its servicing agent to which a credit entry will be made as a result of the payment transaction.
	CreditorAgentAccount *CashAccount16 `xml:"CdtrAgtAcct,omitempty"`

	// Party to which an amount of money is due.
	Creditor *PartyIdentification32 `xml:"Cdtr,omitempty"`

	// Unambiguous identification of the account of the creditor to which a credit entry will be posted as a result of the payment transaction.
	CreditorAccount *CashAccount16 `xml:"CdtrAcct,omitempty"`

	// Ultimate party to which an amount of money is due.
	UltimateCreditor *PartyIdentification32 `xml:"UltmtCdtr,omitempty"`
}

func (o *OriginalTransactionReference13) SetInterbankSettlementAmount(value, currency string) {
	o.InterbankSettlementAmount = NewActiveOrHistoricCurrencyAndAmount(value, currency)
}

func (o *OriginalTransactionReference13) AddAmount() *AmountType3Choice {
	o.Amount = new(AmountType3Choice)
	return o.Amount
}

func (o *OriginalTransactionReference13) SetInterbankSettlementDate(value string) {
	o.InterbankSettlementDate = (*ISODate)(&value)
}

func (o *OriginalTransactionReference13) SetRequestedCollectionDate(value string) {
	o.RequestedCollectionDate = (*ISODate)(&value)
}

func (o *OriginalTransactionReference13) SetRequestedExecutionDate(value string) {
	o.RequestedExecutionDate = (*ISODate)(&value)
}

func (o *OriginalTransactionReference13) AddCreditorSchemeIdentification() *PartyIdentification32 {
	o.CreditorSchemeIdentification = new(PartyIdentification32)
	return o.CreditorSchemeIdentification
}

func (o *OriginalTransactionReference13) AddSettlementInformation() *SettlementInformation13 {
	o.SettlementInformation = new(SettlementInformation13)
	return o.SettlementInformation
}

func (o *OriginalTransactionReference13) AddPaymentTypeInformation() *PaymentTypeInformation22 {
	o.PaymentTypeInformation = new(PaymentTypeInformation22)
	return o.PaymentTypeInformation
}

func (o *OriginalTransactionReference13) SetPaymentMethod(value string) {
	o.PaymentMethod = (*PaymentMethod4Code)(&value)
}

func (o *OriginalTransactionReference13) AddMandateRelatedInformation() *MandateRelatedInformation6 {
	o.MandateRelatedInformation = new(MandateRelatedInformation6)
	return o.MandateRelatedInformation
}

func (o *OriginalTransactionReference13) AddRemittanceInformation() *RemittanceInformation5 {
	o.RemittanceInformation = new(RemittanceInformation5)
	return o.RemittanceInformation
}

func (o *OriginalTransactionReference13) AddUltimateDebtor() *PartyIdentification32 {
	o.UltimateDebtor = new(PartyIdentification32)
	return o.UltimateDebtor
}

func (o *OriginalTransactionReference13) AddDebtor() *PartyIdentification32 {
	o.Debtor = new(PartyIdentification32)
	return o.Debtor
}

func (o *OriginalTransactionReference13) AddDebtorAccount() *CashAccount16 {
	o.DebtorAccount = new(CashAccount16)
	return o.DebtorAccount
}

func (o *OriginalTransactionReference13) AddDebtorAgent() *BranchAndFinancialInstitutionIdentification4 {
	o.DebtorAgent = new(BranchAndFinancialInstitutionIdentification4)
	return o.DebtorAgent
}

func (o *OriginalTransactionReference13) AddDebtorAgentAccount() *CashAccount16 {
	o.DebtorAgentAccount = new(CashAccount16)
	return o.DebtorAgentAccount
}

func (o *OriginalTransactionReference13) AddCreditorAgent() *BranchAndFinancialInstitutionIdentification4 {
	o.CreditorAgent = new(BranchAndFinancialInstitutionIdentification4)
	return o.CreditorAgent
}

func (o *OriginalTransactionReference13) AddCreditorAgentAccount() *CashAccount16 {
	o.CreditorAgentAccount = new(CashAccount16)
	return o.CreditorAgentAccount
}

func (o *OriginalTransactionReference13) AddCreditor() *PartyIdentification32 {
	o.Creditor = new(PartyIdentification32)
	return o.Creditor
}

func (o *OriginalTransactionReference13) AddCreditorAccount() *CashAccount16 {
	o.CreditorAccount = new(CashAccount16)
	return o.CreditorAccount
}

func (o *OriginalTransactionReference13) AddUltimateCreditor() *PartyIdentification32 {
	o.UltimateCreditor = new(PartyIdentification32)
	return o.UltimateCreditor
}
